/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/acquisitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Acquisitions */
        get: operations["get_acquisitions_acquisitions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acquisitions/{acquisition_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Acquisition */
        get: operations["get_acquisition_acquisitions__acquisition_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/grids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Grids */
        get: operations["get_grids_grids_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/grids/{grid_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Grid */
        get: operations["get_grid_grids__grid_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acquisitions/{acquisition_id}/grids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Acquisition Grids */
        get: operations["get_acquisition_grids_acquisitions__acquisition_id__grids_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gridsquares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Gridsquares */
        get: operations["get_gridsquares_gridsquares_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gridsquares/{gridsquare_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Gridsquare */
        get: operations["get_gridsquare_gridsquares__gridsquare_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/grids/{grid_id}/gridsquares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Grid Gridsquares */
        get: operations["get_grid_gridsquares_grids__grid_id__gridsquares_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/foilholes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Foilholes */
        get: operations["get_foilholes_foilholes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/foilholes/{foilhole_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Foilhole */
        get: operations["get_foilhole_foilholes__foilhole_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gridsquares/{gridsquare_id}/foilholes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Gridsquare Foilholes */
        get: operations["get_gridsquare_foilholes_gridsquares__gridsquare_id__foilholes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/micrographs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Micrographs */
        get: operations["get_micrographs_micrographs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/micrographs/{micrograph_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Micrograph */
        get: operations["get_micrograph_micrographs__micrograph_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/foilholes/{foilhole_id}/micrographs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Foilhole Micrographs */
        get: operations["get_foilhole_micrographs_foilholes__foilhole_id__micrographs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gridsquares/{gridsquare_id}/quality_predictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Quality Predictions For Square */
        get: operations["get_quality_predictions_for_square_gridsquares__gridsquare_id__quality_predictions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prediction_models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stored Prediction Models */
        get: operations["get_stored_prediction_models_prediction_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prediction_models/{model_name}/grids/{grid_id}/weights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Model Weights */
        get: operations["get_model_weights_prediction_models__model_name__grids__grid_id__weights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gridsquares/{gridsquare_id}/weigthed_predictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calculate Weighted Predictions */
        get: operations["calculate_weighted_predictions_gridsquares__gridsquare_id__weigthed_predictions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gridsquares/{gridsquare_id}/most_recent_quality_prediction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Most Recent Quality Prediction For Square */
        get: operations["get_most_recent_quality_prediction_for_square_gridsquares__gridsquare_id__most_recent_quality_prediction_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/foilholes/{foilhole_id}/quality_predictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Quality Predictions For Hole */
        get: operations["get_quality_predictions_for_hole_foilholes__foilhole_id__quality_predictions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcquisitionResponse */
        AcquisitionResponse: {
            /** Id */
            id: number;
            /** Epu Id */
            epu_id: string | null;
            /** Name */
            name: string;
            status: components["schemas"]["AcquisitionStatus"];
            /** Start Time */
            start_time: string | null;
            /** End Time */
            end_time: string | null;
            /** Paused Time */
            paused_time: string | null;
        };
        /**
         * AcquisitionStatus
         * @enum {string}
         */
        AcquisitionStatus: "planned" | "started" | "completed" | "paused" | "abandoned";
        /** FoilHoleResponse */
        FoilHoleResponse: {
            /** Id */
            id: number;
            /** Gridsquare Id */
            gridsquare_id: number | null;
            status: components["schemas"]["FoilHoleStatus"];
            /** Name */
            name: string;
        };
        /**
         * FoilHoleStatus
         * @enum {string}
         */
        FoilHoleStatus: "none" | "micrographs detected";
        /** Grid */
        Grid: {
            /** Id */
            id?: number | null;
            /** Acquisition Id */
            acquisition_id?: number | null;
            /** @default none */
            status: components["schemas"]["GridStatus"];
            /** Name */
            name: string;
            /** Scan Start Time */
            scan_start_time?: string | null;
            /** Scan End Time */
            scan_end_time?: string | null;
        };
        /** GridResponse */
        GridResponse: {
            /** Id */
            id: number;
            /** Acquisition Id */
            acquisition_id: number | null;
            status: components["schemas"]["GridStatus"];
            /** Name */
            name: string;
            /** Scan Start Time */
            scan_start_time: string | null;
            /** Scan End Time */
            scan_end_time: string | null;
        };
        /** GridSquareResponse */
        GridSquareResponse: {
            /** Id */
            id: number;
            /** Grid Id */
            grid_id: number | null;
            status: components["schemas"]["GridSquareStatus"];
            /** Atlastile Img */
            atlastile_img: string;
            /** Name */
            name: string;
        };
        /**
         * GridSquareStatus
         * @enum {string}
         */
        GridSquareStatus: "none" | "foil holes decision started" | "foil holes decision completed";
        /**
         * GridStatus
         * @enum {string}
         */
        GridStatus: "none" | "scan started" | "scan completed" | "grid squares decision started" | "grid squares decision completed";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MicrographResponse */
        MicrographResponse: {
            /** Id */
            id: number;
            /** Foilhole Id */
            foilhole_id: number | null;
            status: components["schemas"]["MicrographStatus"];
            /** Total Motion */
            total_motion: number | null;
            /** Average Motion */
            average_motion: number | null;
            /** Ctf Max Resolution Estimate */
            ctf_max_resolution_estimate: number | null;
            /** Number Of Particles Selected */
            number_of_particles_selected: number | null;
            /** Number Of Particles Rejected */
            number_of_particles_rejected: number | null;
            /** Selection Distribution */
            selection_distribution: string | null;
            /** Number Of Particles Picked */
            number_of_particles_picked: number | null;
            /** Pick Distribution */
            pick_distribution: string | null;
        };
        /**
         * MicrographStatus
         * @enum {string}
         */
        MicrographStatus: "none" | "motion correction started" | "motion correction completed" | "ctf started" | "ctf completed" | "particle picking started" | "particle picking completed" | "particle selection started" | "particle selection completed";
        /** ModelWeightResponse */
        ModelWeightResponse: {
            /** Weight */
            weight: number;
            /** Timestamp */
            timestamp: string;
        };
        /** PredictionModelResponse */
        PredictionModelResponse: {
            prediction_model: components["schemas"]["QualityPredictionModel"];
            /** Grids */
            grids: components["schemas"]["Grid"][];
        };
        /** QualityPrediction */
        QualityPrediction: {
            /** Id */
            id?: number | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Value */
            value: number;
            /** Prediction Model Name */
            prediction_model_name: string;
            /** Foilhole Id */
            foilhole_id?: number | null;
            /** Gridsquare Id */
            gridsquare_id?: number | null;
        };
        /** QualityPredictionModel */
        QualityPredictionModel: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** Score */
        Score: {
            /** Value */
            value: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_acquisitions_acquisitions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcquisitionResponse"][];
                };
            };
        };
    };
    get_acquisition_acquisitions__acquisition_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                acquisition_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcquisitionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_grids_grids_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GridResponse"][];
                };
            };
        };
    };
    get_grid_grids__grid_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                grid_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GridResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_acquisition_grids_acquisitions__acquisition_id__grids_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                acquisition_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GridResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_gridsquares_gridsquares_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GridSquareResponse"][];
                };
            };
        };
    };
    get_gridsquare_gridsquares__gridsquare_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gridsquare_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GridSquareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_grid_gridsquares_grids__grid_id__gridsquares_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                grid_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GridSquareResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_foilholes_foilholes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoilHoleResponse"][];
                };
            };
        };
    };
    get_foilhole_foilholes__foilhole_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                foilhole_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoilHoleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_gridsquare_foilholes_gridsquares__gridsquare_id__foilholes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gridsquare_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoilHoleResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_micrographs_micrographs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MicrographResponse"][];
                };
            };
        };
    };
    get_micrograph_micrographs__micrograph_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                micrograph_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MicrographResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_foilhole_micrographs_foilholes__foilhole_id__micrographs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                foilhole_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MicrographResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quality_predictions_for_square_gridsquares__gridsquare_id__quality_predictions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gridsquare_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["QualityPrediction"][][];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stored_prediction_models_prediction_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionModelResponse"][];
                };
            };
        };
    };
    get_model_weights_prediction_models__model_name__grids__grid_id__weights_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_name: string;
                grid_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelWeightResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calculate_weighted_predictions_gridsquares__gridsquare_id__weigthed_predictions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gridsquare_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["Score"][];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_most_recent_quality_prediction_for_square_gridsquares__gridsquare_id__most_recent_quality_prediction_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gridsquare_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["QualityPrediction"][];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quality_predictions_for_hole_foilholes__foilhole_id__quality_predictions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                foilhole_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["QualityPrediction"][];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
