/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AcquisitionsAcqIdRouteImport } from './routes/acquisitions.$acqId'
import { Route as AcquisitionsAcqIdGridsGridIdAtlasRouteImport } from './routes/acquisitions.$acqId.grids.$gridId.atlas'
import { Route as AcquisitionsAcqIdGridsGridIdGridsquaresRouteImport } from './routes/acquisitions.$acqId.grids.$gridId.gridsquares'
import { Route as AcquisitionsAcqIdGridsGridIdIndexRouteImport } from './routes/acquisitions.$acqId.grids.$gridId.index'
import { Route as AcquisitionsAcqIdGridsGridIdSquareSquareIdPredictionsRouteImport } from './routes/acquisitions.$acqId.grids.$gridId.square.$squareId.predictions'
import { Route as AcquisitionsAcqIdGridsGridIdSquaresSquareIdRouteImport } from './routes/acquisitions.$acqId.grids.$gridId.squares.$squareId'
import { Route as AcquisitionsAcqIdGridsGridIdWorkspaceRouteImport } from './routes/acquisitions.$acqId.grids.$gridId.workspace'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as ModelsModelNameGridsGridIdWeightsRouteImport } from './routes/models.$modelName.grids.$gridId.weights'

const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcquisitionsAcqIdRoute = AcquisitionsAcqIdRouteImport.update({
  id: '/acquisitions/$acqId',
  path: '/acquisitions/$acqId',
  getParentRoute: () => rootRouteImport,
} as any)
const AcquisitionsAcqIdGridsGridIdIndexRoute =
  AcquisitionsAcqIdGridsGridIdIndexRouteImport.update({
    id: '/grids/$gridId/',
    path: '/grids/$gridId/',
    getParentRoute: () => AcquisitionsAcqIdRoute,
  } as any)
const ModelsModelNameGridsGridIdWeightsRoute =
  ModelsModelNameGridsGridIdWeightsRouteImport.update({
    id: '/$modelName/grids/$gridId/weights',
    path: '/$modelName/grids/$gridId/weights',
    getParentRoute: () => ModelsRoute,
  } as any)
const AcquisitionsAcqIdGridsGridIdWorkspaceRoute =
  AcquisitionsAcqIdGridsGridIdWorkspaceRouteImport.update({
    id: '/grids/$gridId/workspace',
    path: '/grids/$gridId/workspace',
    getParentRoute: () => AcquisitionsAcqIdRoute,
  } as any)
const AcquisitionsAcqIdGridsGridIdGridsquaresRoute =
  AcquisitionsAcqIdGridsGridIdGridsquaresRouteImport.update({
    id: '/grids/$gridId/gridsquares',
    path: '/grids/$gridId/gridsquares',
    getParentRoute: () => AcquisitionsAcqIdRoute,
  } as any)
const AcquisitionsAcqIdGridsGridIdAtlasRoute =
  AcquisitionsAcqIdGridsGridIdAtlasRouteImport.update({
    id: '/grids/$gridId/atlas',
    path: '/grids/$gridId/atlas',
    getParentRoute: () => AcquisitionsAcqIdRoute,
  } as any)
const AcquisitionsAcqIdGridsGridIdSquaresSquareIdRoute =
  AcquisitionsAcqIdGridsGridIdSquaresSquareIdRouteImport.update({
    id: '/grids/$gridId/squares/$squareId',
    path: '/grids/$gridId/squares/$squareId',
    getParentRoute: () => AcquisitionsAcqIdRoute,
  } as any)
const AcquisitionsAcqIdGridsGridIdSquareSquareIdPredictionsRoute =
  AcquisitionsAcqIdGridsGridIdSquareSquareIdPredictionsRouteImport.update({
    id: '/grids/$gridId/square/$squareId/predictions',
    path: '/grids/$gridId/square/$squareId/predictions',
    getParentRoute: () => AcquisitionsAcqIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/models': typeof ModelsRouteWithChildren
  '/acquisitions/$acqId': typeof AcquisitionsAcqIdRouteWithChildren
  '/acquisitions/$acqId/grids/$gridId/atlas': typeof AcquisitionsAcqIdGridsGridIdAtlasRoute
  '/acquisitions/$acqId/grids/$gridId/gridsquares': typeof AcquisitionsAcqIdGridsGridIdGridsquaresRoute
  '/acquisitions/$acqId/grids/$gridId/workspace': typeof AcquisitionsAcqIdGridsGridIdWorkspaceRoute
  '/models/$modelName/grids/$gridId/weights': typeof ModelsModelNameGridsGridIdWeightsRoute
  '/acquisitions/$acqId/grids/$gridId/': typeof AcquisitionsAcqIdGridsGridIdIndexRoute
  '/acquisitions/$acqId/grids/$gridId/squares/$squareId': typeof AcquisitionsAcqIdGridsGridIdSquaresSquareIdRoute
  '/acquisitions/$acqId/grids/$gridId/square/$squareId/predictions': typeof AcquisitionsAcqIdGridsGridIdSquareSquareIdPredictionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/models': typeof ModelsRouteWithChildren
  '/acquisitions/$acqId': typeof AcquisitionsAcqIdRouteWithChildren
  '/acquisitions/$acqId/grids/$gridId/atlas': typeof AcquisitionsAcqIdGridsGridIdAtlasRoute
  '/acquisitions/$acqId/grids/$gridId/gridsquares': typeof AcquisitionsAcqIdGridsGridIdGridsquaresRoute
  '/acquisitions/$acqId/grids/$gridId/workspace': typeof AcquisitionsAcqIdGridsGridIdWorkspaceRoute
  '/models/$modelName/grids/$gridId/weights': typeof ModelsModelNameGridsGridIdWeightsRoute
  '/acquisitions/$acqId/grids/$gridId': typeof AcquisitionsAcqIdGridsGridIdIndexRoute
  '/acquisitions/$acqId/grids/$gridId/squares/$squareId': typeof AcquisitionsAcqIdGridsGridIdSquaresSquareIdRoute
  '/acquisitions/$acqId/grids/$gridId/square/$squareId/predictions': typeof AcquisitionsAcqIdGridsGridIdSquareSquareIdPredictionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/models': typeof ModelsRouteWithChildren
  '/acquisitions/$acqId': typeof AcquisitionsAcqIdRouteWithChildren
  '/acquisitions/$acqId/grids/$gridId/atlas': typeof AcquisitionsAcqIdGridsGridIdAtlasRoute
  '/acquisitions/$acqId/grids/$gridId/gridsquares': typeof AcquisitionsAcqIdGridsGridIdGridsquaresRoute
  '/acquisitions/$acqId/grids/$gridId/workspace': typeof AcquisitionsAcqIdGridsGridIdWorkspaceRoute
  '/models/$modelName/grids/$gridId/weights': typeof ModelsModelNameGridsGridIdWeightsRoute
  '/acquisitions/$acqId/grids/$gridId/': typeof AcquisitionsAcqIdGridsGridIdIndexRoute
  '/acquisitions/$acqId/grids/$gridId/squares/$squareId': typeof AcquisitionsAcqIdGridsGridIdSquaresSquareIdRoute
  '/acquisitions/$acqId/grids/$gridId/square/$squareId/predictions': typeof AcquisitionsAcqIdGridsGridIdSquareSquareIdPredictionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/models'
    | '/acquisitions/$acqId'
    | '/acquisitions/$acqId/grids/$gridId/atlas'
    | '/acquisitions/$acqId/grids/$gridId/gridsquares'
    | '/acquisitions/$acqId/grids/$gridId/workspace'
    | '/models/$modelName/grids/$gridId/weights'
    | '/acquisitions/$acqId/grids/$gridId/'
    | '/acquisitions/$acqId/grids/$gridId/squares/$squareId'
    | '/acquisitions/$acqId/grids/$gridId/square/$squareId/predictions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/models'
    | '/acquisitions/$acqId'
    | '/acquisitions/$acqId/grids/$gridId/atlas'
    | '/acquisitions/$acqId/grids/$gridId/gridsquares'
    | '/acquisitions/$acqId/grids/$gridId/workspace'
    | '/models/$modelName/grids/$gridId/weights'
    | '/acquisitions/$acqId/grids/$gridId'
    | '/acquisitions/$acqId/grids/$gridId/squares/$squareId'
    | '/acquisitions/$acqId/grids/$gridId/square/$squareId/predictions'
  id:
    | '__root__'
    | '/'
    | '/models'
    | '/acquisitions/$acqId'
    | '/acquisitions/$acqId/grids/$gridId/atlas'
    | '/acquisitions/$acqId/grids/$gridId/gridsquares'
    | '/acquisitions/$acqId/grids/$gridId/workspace'
    | '/models/$modelName/grids/$gridId/weights'
    | '/acquisitions/$acqId/grids/$gridId/'
    | '/acquisitions/$acqId/grids/$gridId/squares/$squareId'
    | '/acquisitions/$acqId/grids/$gridId/square/$squareId/predictions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModelsRoute: typeof ModelsRouteWithChildren
  AcquisitionsAcqIdRoute: typeof AcquisitionsAcqIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acquisitions/$acqId': {
      id: '/acquisitions/$acqId'
      path: '/acquisitions/$acqId'
      fullPath: '/acquisitions/$acqId'
      preLoaderRoute: typeof AcquisitionsAcqIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acquisitions/$acqId/grids/$gridId/': {
      id: '/acquisitions/$acqId/grids/$gridId/'
      path: '/grids/$gridId'
      fullPath: '/acquisitions/$acqId/grids/$gridId/'
      preLoaderRoute: typeof AcquisitionsAcqIdGridsGridIdIndexRouteImport
      parentRoute: typeof AcquisitionsAcqIdRoute
    }
    '/models/$modelName/grids/$gridId/weights': {
      id: '/models/$modelName/grids/$gridId/weights'
      path: '/$modelName/grids/$gridId/weights'
      fullPath: '/models/$modelName/grids/$gridId/weights'
      preLoaderRoute: typeof ModelsModelNameGridsGridIdWeightsRouteImport
      parentRoute: typeof ModelsRoute
    }
    '/acquisitions/$acqId/grids/$gridId/workspace': {
      id: '/acquisitions/$acqId/grids/$gridId/workspace'
      path: '/grids/$gridId/workspace'
      fullPath: '/acquisitions/$acqId/grids/$gridId/workspace'
      preLoaderRoute: typeof AcquisitionsAcqIdGridsGridIdWorkspaceRouteImport
      parentRoute: typeof AcquisitionsAcqIdRoute
    }
    '/acquisitions/$acqId/grids/$gridId/gridsquares': {
      id: '/acquisitions/$acqId/grids/$gridId/gridsquares'
      path: '/grids/$gridId/gridsquares'
      fullPath: '/acquisitions/$acqId/grids/$gridId/gridsquares'
      preLoaderRoute: typeof AcquisitionsAcqIdGridsGridIdGridsquaresRouteImport
      parentRoute: typeof AcquisitionsAcqIdRoute
    }
    '/acquisitions/$acqId/grids/$gridId/atlas': {
      id: '/acquisitions/$acqId/grids/$gridId/atlas'
      path: '/grids/$gridId/atlas'
      fullPath: '/acquisitions/$acqId/grids/$gridId/atlas'
      preLoaderRoute: typeof AcquisitionsAcqIdGridsGridIdAtlasRouteImport
      parentRoute: typeof AcquisitionsAcqIdRoute
    }
    '/acquisitions/$acqId/grids/$gridId/squares/$squareId': {
      id: '/acquisitions/$acqId/grids/$gridId/squares/$squareId'
      path: '/grids/$gridId/squares/$squareId'
      fullPath: '/acquisitions/$acqId/grids/$gridId/squares/$squareId'
      preLoaderRoute: typeof AcquisitionsAcqIdGridsGridIdSquaresSquareIdRouteImport
      parentRoute: typeof AcquisitionsAcqIdRoute
    }
    '/acquisitions/$acqId/grids/$gridId/square/$squareId/predictions': {
      id: '/acquisitions/$acqId/grids/$gridId/square/$squareId/predictions'
      path: '/grids/$gridId/square/$squareId/predictions'
      fullPath: '/acquisitions/$acqId/grids/$gridId/square/$squareId/predictions'
      preLoaderRoute: typeof AcquisitionsAcqIdGridsGridIdSquareSquareIdPredictionsRouteImport
      parentRoute: typeof AcquisitionsAcqIdRoute
    }
  }
}

interface ModelsRouteChildren {
  ModelsModelNameGridsGridIdWeightsRoute: typeof ModelsModelNameGridsGridIdWeightsRoute
}

const ModelsRouteChildren: ModelsRouteChildren = {
  ModelsModelNameGridsGridIdWeightsRoute:
    ModelsModelNameGridsGridIdWeightsRoute,
}

const ModelsRouteWithChildren =
  ModelsRoute._addFileChildren(ModelsRouteChildren)

interface AcquisitionsAcqIdRouteChildren {
  AcquisitionsAcqIdGridsGridIdAtlasRoute: typeof AcquisitionsAcqIdGridsGridIdAtlasRoute
  AcquisitionsAcqIdGridsGridIdGridsquaresRoute: typeof AcquisitionsAcqIdGridsGridIdGridsquaresRoute
  AcquisitionsAcqIdGridsGridIdWorkspaceRoute: typeof AcquisitionsAcqIdGridsGridIdWorkspaceRoute
  AcquisitionsAcqIdGridsGridIdIndexRoute: typeof AcquisitionsAcqIdGridsGridIdIndexRoute
  AcquisitionsAcqIdGridsGridIdSquaresSquareIdRoute: typeof AcquisitionsAcqIdGridsGridIdSquaresSquareIdRoute
  AcquisitionsAcqIdGridsGridIdSquareSquareIdPredictionsRoute: typeof AcquisitionsAcqIdGridsGridIdSquareSquareIdPredictionsRoute
}

const AcquisitionsAcqIdRouteChildren: AcquisitionsAcqIdRouteChildren = {
  AcquisitionsAcqIdGridsGridIdAtlasRoute:
    AcquisitionsAcqIdGridsGridIdAtlasRoute,
  AcquisitionsAcqIdGridsGridIdGridsquaresRoute:
    AcquisitionsAcqIdGridsGridIdGridsquaresRoute,
  AcquisitionsAcqIdGridsGridIdWorkspaceRoute:
    AcquisitionsAcqIdGridsGridIdWorkspaceRoute,
  AcquisitionsAcqIdGridsGridIdIndexRoute:
    AcquisitionsAcqIdGridsGridIdIndexRoute,
  AcquisitionsAcqIdGridsGridIdSquaresSquareIdRoute:
    AcquisitionsAcqIdGridsGridIdSquaresSquareIdRoute,
  AcquisitionsAcqIdGridsGridIdSquareSquareIdPredictionsRoute:
    AcquisitionsAcqIdGridsGridIdSquareSquareIdPredictionsRoute,
}

const AcquisitionsAcqIdRouteWithChildren =
  AcquisitionsAcqIdRoute._addFileChildren(AcquisitionsAcqIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModelsRoute: ModelsRouteWithChildren,
  AcquisitionsAcqIdRoute: AcquisitionsAcqIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
