/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions.index'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId'
import { Route as SessionsSessionIdIndexRouteImport } from './routes/sessions.$sessionId.index'
import { Route as SessionsSessionIdGridsGridIdRouteImport } from './routes/sessions.$sessionId.grids.$gridId'
import { Route as SessionsSessionIdGridsGridIdIndexRouteImport } from './routes/sessions.$sessionId.grids.$gridId.index'
import { Route as SessionsSessionIdGridsGridIdWorkspaceRouteImport } from './routes/sessions.$sessionId.grids.$gridId.workspace'
import { Route as SessionsSessionIdGridsGridIdSquaresRouteImport } from './routes/sessions.$sessionId.grids.$gridId.squares'
import { Route as SessionsSessionIdGridsGridIdPredictionsRouteImport } from './routes/sessions.$sessionId.grids.$gridId.predictions'
import { Route as SessionsSessionIdGridsGridIdAtlasRouteImport } from './routes/sessions.$sessionId.grids.$gridId.atlas'
import { Route as SessionsSessionIdGridsGridIdSquaresSquareIdRouteImport } from './routes/sessions.$sessionId.grids.$gridId.squares_.$squareId'
import { Route as SessionsSessionIdGridsGridIdSquaresSquareIdIndexRouteImport } from './routes/sessions.$sessionId.grids.$gridId.squares_.$squareId.index'
import { Route as SessionsSessionIdGridsGridIdSquaresSquareIdHolesHoleIdRouteImport } from './routes/sessions.$sessionId.grids.$gridId.squares_.$squareId.holes_.$holeId'

const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionsRoute,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => SessionsRoute,
} as any)
const SessionsSessionIdIndexRoute = SessionsSessionIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionsSessionIdRoute,
} as any)
const SessionsSessionIdGridsGridIdRoute =
  SessionsSessionIdGridsGridIdRouteImport.update({
    id: '/grids/$gridId',
    path: '/grids/$gridId',
    getParentRoute: () => SessionsSessionIdRoute,
  } as any)
const SessionsSessionIdGridsGridIdIndexRoute =
  SessionsSessionIdGridsGridIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SessionsSessionIdGridsGridIdRoute,
  } as any)
const SessionsSessionIdGridsGridIdWorkspaceRoute =
  SessionsSessionIdGridsGridIdWorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => SessionsSessionIdGridsGridIdRoute,
  } as any)
const SessionsSessionIdGridsGridIdSquaresRoute =
  SessionsSessionIdGridsGridIdSquaresRouteImport.update({
    id: '/squares',
    path: '/squares',
    getParentRoute: () => SessionsSessionIdGridsGridIdRoute,
  } as any)
const SessionsSessionIdGridsGridIdPredictionsRoute =
  SessionsSessionIdGridsGridIdPredictionsRouteImport.update({
    id: '/predictions',
    path: '/predictions',
    getParentRoute: () => SessionsSessionIdGridsGridIdRoute,
  } as any)
const SessionsSessionIdGridsGridIdAtlasRoute =
  SessionsSessionIdGridsGridIdAtlasRouteImport.update({
    id: '/atlas',
    path: '/atlas',
    getParentRoute: () => SessionsSessionIdGridsGridIdRoute,
  } as any)
const SessionsSessionIdGridsGridIdSquaresSquareIdRoute =
  SessionsSessionIdGridsGridIdSquaresSquareIdRouteImport.update({
    id: '/squares_/$squareId',
    path: '/squares/$squareId',
    getParentRoute: () => SessionsSessionIdGridsGridIdRoute,
  } as any)
const SessionsSessionIdGridsGridIdSquaresSquareIdIndexRoute =
  SessionsSessionIdGridsGridIdSquaresSquareIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SessionsSessionIdGridsGridIdSquaresSquareIdRoute,
  } as any)
const SessionsSessionIdGridsGridIdSquaresSquareIdHolesHoleIdRoute =
  SessionsSessionIdGridsGridIdSquaresSquareIdHolesHoleIdRouteImport.update({
    id: '/holes_/$holeId',
    path: '/holes/$holeId',
    getParentRoute: () => SessionsSessionIdGridsGridIdSquaresSquareIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/sessions/$sessionId': typeof SessionsSessionIdRouteWithChildren
  '/sessions/': typeof SessionsIndexRoute
  '/sessions/$sessionId/': typeof SessionsSessionIdIndexRoute
  '/sessions/$sessionId/grids/$gridId': typeof SessionsSessionIdGridsGridIdRouteWithChildren
  '/sessions/$sessionId/grids/$gridId/atlas': typeof SessionsSessionIdGridsGridIdAtlasRoute
  '/sessions/$sessionId/grids/$gridId/predictions': typeof SessionsSessionIdGridsGridIdPredictionsRoute
  '/sessions/$sessionId/grids/$gridId/squares': typeof SessionsSessionIdGridsGridIdSquaresRoute
  '/sessions/$sessionId/grids/$gridId/workspace': typeof SessionsSessionIdGridsGridIdWorkspaceRoute
  '/sessions/$sessionId/grids/$gridId/': typeof SessionsSessionIdGridsGridIdIndexRoute
  '/sessions/$sessionId/grids/$gridId/squares/$squareId': typeof SessionsSessionIdGridsGridIdSquaresSquareIdRouteWithChildren
  '/sessions/$sessionId/grids/$gridId/squares/$squareId/': typeof SessionsSessionIdGridsGridIdSquaresSquareIdIndexRoute
  '/sessions/$sessionId/grids/$gridId/squares/$squareId/holes/$holeId': typeof SessionsSessionIdGridsGridIdSquaresSquareIdHolesHoleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/sessions/$sessionId': typeof SessionsSessionIdIndexRoute
  '/sessions/$sessionId/grids/$gridId/atlas': typeof SessionsSessionIdGridsGridIdAtlasRoute
  '/sessions/$sessionId/grids/$gridId/predictions': typeof SessionsSessionIdGridsGridIdPredictionsRoute
  '/sessions/$sessionId/grids/$gridId/squares': typeof SessionsSessionIdGridsGridIdSquaresRoute
  '/sessions/$sessionId/grids/$gridId/workspace': typeof SessionsSessionIdGridsGridIdWorkspaceRoute
  '/sessions/$sessionId/grids/$gridId': typeof SessionsSessionIdGridsGridIdIndexRoute
  '/sessions/$sessionId/grids/$gridId/squares/$squareId': typeof SessionsSessionIdGridsGridIdSquaresSquareIdIndexRoute
  '/sessions/$sessionId/grids/$gridId/squares/$squareId/holes/$holeId': typeof SessionsSessionIdGridsGridIdSquaresSquareIdHolesHoleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/sessions/$sessionId': typeof SessionsSessionIdRouteWithChildren
  '/sessions/': typeof SessionsIndexRoute
  '/sessions/$sessionId/': typeof SessionsSessionIdIndexRoute
  '/sessions/$sessionId/grids/$gridId': typeof SessionsSessionIdGridsGridIdRouteWithChildren
  '/sessions/$sessionId/grids/$gridId/atlas': typeof SessionsSessionIdGridsGridIdAtlasRoute
  '/sessions/$sessionId/grids/$gridId/predictions': typeof SessionsSessionIdGridsGridIdPredictionsRoute
  '/sessions/$sessionId/grids/$gridId/squares': typeof SessionsSessionIdGridsGridIdSquaresRoute
  '/sessions/$sessionId/grids/$gridId/workspace': typeof SessionsSessionIdGridsGridIdWorkspaceRoute
  '/sessions/$sessionId/grids/$gridId/': typeof SessionsSessionIdGridsGridIdIndexRoute
  '/sessions/$sessionId/grids/$gridId/squares_/$squareId': typeof SessionsSessionIdGridsGridIdSquaresSquareIdRouteWithChildren
  '/sessions/$sessionId/grids/$gridId/squares_/$squareId/': typeof SessionsSessionIdGridsGridIdSquaresSquareIdIndexRoute
  '/sessions/$sessionId/grids/$gridId/squares_/$squareId/holes_/$holeId': typeof SessionsSessionIdGridsGridIdSquaresSquareIdHolesHoleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sessions'
    | '/sessions/$sessionId'
    | '/sessions/'
    | '/sessions/$sessionId/'
    | '/sessions/$sessionId/grids/$gridId'
    | '/sessions/$sessionId/grids/$gridId/atlas'
    | '/sessions/$sessionId/grids/$gridId/predictions'
    | '/sessions/$sessionId/grids/$gridId/squares'
    | '/sessions/$sessionId/grids/$gridId/workspace'
    | '/sessions/$sessionId/grids/$gridId/'
    | '/sessions/$sessionId/grids/$gridId/squares/$squareId'
    | '/sessions/$sessionId/grids/$gridId/squares/$squareId/'
    | '/sessions/$sessionId/grids/$gridId/squares/$squareId/holes/$holeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sessions'
    | '/sessions/$sessionId'
    | '/sessions/$sessionId/grids/$gridId/atlas'
    | '/sessions/$sessionId/grids/$gridId/predictions'
    | '/sessions/$sessionId/grids/$gridId/squares'
    | '/sessions/$sessionId/grids/$gridId/workspace'
    | '/sessions/$sessionId/grids/$gridId'
    | '/sessions/$sessionId/grids/$gridId/squares/$squareId'
    | '/sessions/$sessionId/grids/$gridId/squares/$squareId/holes/$holeId'
  id:
    | '__root__'
    | '/'
    | '/sessions'
    | '/sessions/$sessionId'
    | '/sessions/'
    | '/sessions/$sessionId/'
    | '/sessions/$sessionId/grids/$gridId'
    | '/sessions/$sessionId/grids/$gridId/atlas'
    | '/sessions/$sessionId/grids/$gridId/predictions'
    | '/sessions/$sessionId/grids/$gridId/squares'
    | '/sessions/$sessionId/grids/$gridId/workspace'
    | '/sessions/$sessionId/grids/$gridId/'
    | '/sessions/$sessionId/grids/$gridId/squares_/$squareId'
    | '/sessions/$sessionId/grids/$gridId/squares_/$squareId/'
    | '/sessions/$sessionId/grids/$gridId/squares_/$squareId/holes_/$holeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SessionsRoute: typeof SessionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/sessions/$sessionId/': {
      id: '/sessions/$sessionId/'
      path: '/'
      fullPath: '/sessions/$sessionId/'
      preLoaderRoute: typeof SessionsSessionIdIndexRouteImport
      parentRoute: typeof SessionsSessionIdRoute
    }
    '/sessions/$sessionId/grids/$gridId': {
      id: '/sessions/$sessionId/grids/$gridId'
      path: '/grids/$gridId'
      fullPath: '/sessions/$sessionId/grids/$gridId'
      preLoaderRoute: typeof SessionsSessionIdGridsGridIdRouteImport
      parentRoute: typeof SessionsSessionIdRoute
    }
    '/sessions/$sessionId/grids/$gridId/': {
      id: '/sessions/$sessionId/grids/$gridId/'
      path: '/'
      fullPath: '/sessions/$sessionId/grids/$gridId/'
      preLoaderRoute: typeof SessionsSessionIdGridsGridIdIndexRouteImport
      parentRoute: typeof SessionsSessionIdGridsGridIdRoute
    }
    '/sessions/$sessionId/grids/$gridId/workspace': {
      id: '/sessions/$sessionId/grids/$gridId/workspace'
      path: '/workspace'
      fullPath: '/sessions/$sessionId/grids/$gridId/workspace'
      preLoaderRoute: typeof SessionsSessionIdGridsGridIdWorkspaceRouteImport
      parentRoute: typeof SessionsSessionIdGridsGridIdRoute
    }
    '/sessions/$sessionId/grids/$gridId/squares': {
      id: '/sessions/$sessionId/grids/$gridId/squares'
      path: '/squares'
      fullPath: '/sessions/$sessionId/grids/$gridId/squares'
      preLoaderRoute: typeof SessionsSessionIdGridsGridIdSquaresRouteImport
      parentRoute: typeof SessionsSessionIdGridsGridIdRoute
    }
    '/sessions/$sessionId/grids/$gridId/predictions': {
      id: '/sessions/$sessionId/grids/$gridId/predictions'
      path: '/predictions'
      fullPath: '/sessions/$sessionId/grids/$gridId/predictions'
      preLoaderRoute: typeof SessionsSessionIdGridsGridIdPredictionsRouteImport
      parentRoute: typeof SessionsSessionIdGridsGridIdRoute
    }
    '/sessions/$sessionId/grids/$gridId/atlas': {
      id: '/sessions/$sessionId/grids/$gridId/atlas'
      path: '/atlas'
      fullPath: '/sessions/$sessionId/grids/$gridId/atlas'
      preLoaderRoute: typeof SessionsSessionIdGridsGridIdAtlasRouteImport
      parentRoute: typeof SessionsSessionIdGridsGridIdRoute
    }
    '/sessions/$sessionId/grids/$gridId/squares_/$squareId': {
      id: '/sessions/$sessionId/grids/$gridId/squares_/$squareId'
      path: '/squares/$squareId'
      fullPath: '/sessions/$sessionId/grids/$gridId/squares/$squareId'
      preLoaderRoute: typeof SessionsSessionIdGridsGridIdSquaresSquareIdRouteImport
      parentRoute: typeof SessionsSessionIdGridsGridIdRoute
    }
    '/sessions/$sessionId/grids/$gridId/squares_/$squareId/': {
      id: '/sessions/$sessionId/grids/$gridId/squares_/$squareId/'
      path: '/'
      fullPath: '/sessions/$sessionId/grids/$gridId/squares/$squareId/'
      preLoaderRoute: typeof SessionsSessionIdGridsGridIdSquaresSquareIdIndexRouteImport
      parentRoute: typeof SessionsSessionIdGridsGridIdSquaresSquareIdRoute
    }
    '/sessions/$sessionId/grids/$gridId/squares_/$squareId/holes_/$holeId': {
      id: '/sessions/$sessionId/grids/$gridId/squares_/$squareId/holes_/$holeId'
      path: '/holes/$holeId'
      fullPath: '/sessions/$sessionId/grids/$gridId/squares/$squareId/holes/$holeId'
      preLoaderRoute: typeof SessionsSessionIdGridsGridIdSquaresSquareIdHolesHoleIdRouteImport
      parentRoute: typeof SessionsSessionIdGridsGridIdSquaresSquareIdRoute
    }
  }
}

interface SessionsSessionIdGridsGridIdSquaresSquareIdRouteChildren {
  SessionsSessionIdGridsGridIdSquaresSquareIdIndexRoute: typeof SessionsSessionIdGridsGridIdSquaresSquareIdIndexRoute
  SessionsSessionIdGridsGridIdSquaresSquareIdHolesHoleIdRoute: typeof SessionsSessionIdGridsGridIdSquaresSquareIdHolesHoleIdRoute
}

const SessionsSessionIdGridsGridIdSquaresSquareIdRouteChildren: SessionsSessionIdGridsGridIdSquaresSquareIdRouteChildren =
  {
    SessionsSessionIdGridsGridIdSquaresSquareIdIndexRoute:
      SessionsSessionIdGridsGridIdSquaresSquareIdIndexRoute,
    SessionsSessionIdGridsGridIdSquaresSquareIdHolesHoleIdRoute:
      SessionsSessionIdGridsGridIdSquaresSquareIdHolesHoleIdRoute,
  }

const SessionsSessionIdGridsGridIdSquaresSquareIdRouteWithChildren =
  SessionsSessionIdGridsGridIdSquaresSquareIdRoute._addFileChildren(
    SessionsSessionIdGridsGridIdSquaresSquareIdRouteChildren,
  )

interface SessionsSessionIdGridsGridIdRouteChildren {
  SessionsSessionIdGridsGridIdAtlasRoute: typeof SessionsSessionIdGridsGridIdAtlasRoute
  SessionsSessionIdGridsGridIdPredictionsRoute: typeof SessionsSessionIdGridsGridIdPredictionsRoute
  SessionsSessionIdGridsGridIdSquaresRoute: typeof SessionsSessionIdGridsGridIdSquaresRoute
  SessionsSessionIdGridsGridIdWorkspaceRoute: typeof SessionsSessionIdGridsGridIdWorkspaceRoute
  SessionsSessionIdGridsGridIdIndexRoute: typeof SessionsSessionIdGridsGridIdIndexRoute
  SessionsSessionIdGridsGridIdSquaresSquareIdRoute: typeof SessionsSessionIdGridsGridIdSquaresSquareIdRouteWithChildren
}

const SessionsSessionIdGridsGridIdRouteChildren: SessionsSessionIdGridsGridIdRouteChildren =
  {
    SessionsSessionIdGridsGridIdAtlasRoute:
      SessionsSessionIdGridsGridIdAtlasRoute,
    SessionsSessionIdGridsGridIdPredictionsRoute:
      SessionsSessionIdGridsGridIdPredictionsRoute,
    SessionsSessionIdGridsGridIdSquaresRoute:
      SessionsSessionIdGridsGridIdSquaresRoute,
    SessionsSessionIdGridsGridIdWorkspaceRoute:
      SessionsSessionIdGridsGridIdWorkspaceRoute,
    SessionsSessionIdGridsGridIdIndexRoute:
      SessionsSessionIdGridsGridIdIndexRoute,
    SessionsSessionIdGridsGridIdSquaresSquareIdRoute:
      SessionsSessionIdGridsGridIdSquaresSquareIdRouteWithChildren,
  }

const SessionsSessionIdGridsGridIdRouteWithChildren =
  SessionsSessionIdGridsGridIdRoute._addFileChildren(
    SessionsSessionIdGridsGridIdRouteChildren,
  )

interface SessionsSessionIdRouteChildren {
  SessionsSessionIdIndexRoute: typeof SessionsSessionIdIndexRoute
  SessionsSessionIdGridsGridIdRoute: typeof SessionsSessionIdGridsGridIdRouteWithChildren
}

const SessionsSessionIdRouteChildren: SessionsSessionIdRouteChildren = {
  SessionsSessionIdIndexRoute: SessionsSessionIdIndexRoute,
  SessionsSessionIdGridsGridIdRoute:
    SessionsSessionIdGridsGridIdRouteWithChildren,
}

const SessionsSessionIdRouteWithChildren =
  SessionsSessionIdRoute._addFileChildren(SessionsSessionIdRouteChildren)

interface SessionsRouteChildren {
  SessionsSessionIdRoute: typeof SessionsSessionIdRouteWithChildren
  SessionsIndexRoute: typeof SessionsIndexRoute
}

const SessionsRouteChildren: SessionsRouteChildren = {
  SessionsSessionIdRoute: SessionsSessionIdRouteWithChildren,
  SessionsIndexRoute: SessionsIndexRoute,
}

const SessionsRouteWithChildren = SessionsRoute._addFileChildren(
  SessionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SessionsRoute: SessionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
