/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AcquisitionsRouteImport } from './routes/acquisitions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcquisitionsIndexRouteImport } from './routes/acquisitions.index'
import { Route as AcquisitionsAcquisitionIdRouteImport } from './routes/acquisitions.$acquisitionId'
import { Route as AcquisitionsAcquisitionIdIndexRouteImport } from './routes/acquisitions.$acquisitionId.index'
import { Route as AcquisitionsAcquisitionIdGridsGridIdRouteImport } from './routes/acquisitions.$acquisitionId.grids.$gridId'
import { Route as AcquisitionsAcquisitionIdGridsGridIdIndexRouteImport } from './routes/acquisitions.$acquisitionId.grids.$gridId.index'
import { Route as AcquisitionsAcquisitionIdGridsGridIdWorkspaceRouteImport } from './routes/acquisitions.$acquisitionId.grids.$gridId.workspace'
import { Route as AcquisitionsAcquisitionIdGridsGridIdSquaresRouteImport } from './routes/acquisitions.$acquisitionId.grids.$gridId.squares'
import { Route as AcquisitionsAcquisitionIdGridsGridIdPredictionsRouteImport } from './routes/acquisitions.$acquisitionId.grids.$gridId.predictions'
import { Route as AcquisitionsAcquisitionIdGridsGridIdAtlasRouteImport } from './routes/acquisitions.$acquisitionId.grids.$gridId.atlas'
import { Route as AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdRouteImport } from './routes/acquisitions.$acquisitionId.grids.$gridId.squares_.$squareId'
import { Route as AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdIndexRouteImport } from './routes/acquisitions.$acquisitionId.grids.$gridId.squares_.$squareId.index'
import { Route as AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdHolesHoleIdRouteImport } from './routes/acquisitions.$acquisitionId.grids.$gridId.squares_.$squareId.holes_.$holeId'

const AcquisitionsRoute = AcquisitionsRouteImport.update({
  id: '/acquisitions',
  path: '/acquisitions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcquisitionsIndexRoute = AcquisitionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcquisitionsRoute,
} as any)
const AcquisitionsAcquisitionIdRoute =
  AcquisitionsAcquisitionIdRouteImport.update({
    id: '/$acquisitionId',
    path: '/$acquisitionId',
    getParentRoute: () => AcquisitionsRoute,
  } as any)
const AcquisitionsAcquisitionIdIndexRoute =
  AcquisitionsAcquisitionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AcquisitionsAcquisitionIdRoute,
  } as any)
const AcquisitionsAcquisitionIdGridsGridIdRoute =
  AcquisitionsAcquisitionIdGridsGridIdRouteImport.update({
    id: '/grids/$gridId',
    path: '/grids/$gridId',
    getParentRoute: () => AcquisitionsAcquisitionIdRoute,
  } as any)
const AcquisitionsAcquisitionIdGridsGridIdIndexRoute =
  AcquisitionsAcquisitionIdGridsGridIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AcquisitionsAcquisitionIdGridsGridIdRoute,
  } as any)
const AcquisitionsAcquisitionIdGridsGridIdWorkspaceRoute =
  AcquisitionsAcquisitionIdGridsGridIdWorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => AcquisitionsAcquisitionIdGridsGridIdRoute,
  } as any)
const AcquisitionsAcquisitionIdGridsGridIdSquaresRoute =
  AcquisitionsAcquisitionIdGridsGridIdSquaresRouteImport.update({
    id: '/squares',
    path: '/squares',
    getParentRoute: () => AcquisitionsAcquisitionIdGridsGridIdRoute,
  } as any)
const AcquisitionsAcquisitionIdGridsGridIdPredictionsRoute =
  AcquisitionsAcquisitionIdGridsGridIdPredictionsRouteImport.update({
    id: '/predictions',
    path: '/predictions',
    getParentRoute: () => AcquisitionsAcquisitionIdGridsGridIdRoute,
  } as any)
const AcquisitionsAcquisitionIdGridsGridIdAtlasRoute =
  AcquisitionsAcquisitionIdGridsGridIdAtlasRouteImport.update({
    id: '/atlas',
    path: '/atlas',
    getParentRoute: () => AcquisitionsAcquisitionIdGridsGridIdRoute,
  } as any)
const AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdRoute =
  AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdRouteImport.update({
    id: '/squares_/$squareId',
    path: '/squares/$squareId',
    getParentRoute: () => AcquisitionsAcquisitionIdGridsGridIdRoute,
  } as any)
const AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdIndexRoute =
  AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdRoute,
  } as any)
const AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdHolesHoleIdRoute =
  AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdHolesHoleIdRouteImport.update(
    {
      id: '/holes_/$holeId',
      path: '/holes/$holeId',
      getParentRoute: () =>
        AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acquisitions': typeof AcquisitionsRouteWithChildren
  '/acquisitions/$acquisitionId': typeof AcquisitionsAcquisitionIdRouteWithChildren
  '/acquisitions/': typeof AcquisitionsIndexRoute
  '/acquisitions/$acquisitionId/': typeof AcquisitionsAcquisitionIdIndexRoute
  '/acquisitions/$acquisitionId/grids/$gridId': typeof AcquisitionsAcquisitionIdGridsGridIdRouteWithChildren
  '/acquisitions/$acquisitionId/grids/$gridId/atlas': typeof AcquisitionsAcquisitionIdGridsGridIdAtlasRoute
  '/acquisitions/$acquisitionId/grids/$gridId/predictions': typeof AcquisitionsAcquisitionIdGridsGridIdPredictionsRoute
  '/acquisitions/$acquisitionId/grids/$gridId/squares': typeof AcquisitionsAcquisitionIdGridsGridIdSquaresRoute
  '/acquisitions/$acquisitionId/grids/$gridId/workspace': typeof AcquisitionsAcquisitionIdGridsGridIdWorkspaceRoute
  '/acquisitions/$acquisitionId/grids/$gridId/': typeof AcquisitionsAcquisitionIdGridsGridIdIndexRoute
  '/acquisitions/$acquisitionId/grids/$gridId/squares/$squareId': typeof AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdRouteWithChildren
  '/acquisitions/$acquisitionId/grids/$gridId/squares/$squareId/': typeof AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdIndexRoute
  '/acquisitions/$acquisitionId/grids/$gridId/squares/$squareId/holes/$holeId': typeof AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdHolesHoleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acquisitions': typeof AcquisitionsIndexRoute
  '/acquisitions/$acquisitionId': typeof AcquisitionsAcquisitionIdIndexRoute
  '/acquisitions/$acquisitionId/grids/$gridId/atlas': typeof AcquisitionsAcquisitionIdGridsGridIdAtlasRoute
  '/acquisitions/$acquisitionId/grids/$gridId/predictions': typeof AcquisitionsAcquisitionIdGridsGridIdPredictionsRoute
  '/acquisitions/$acquisitionId/grids/$gridId/squares': typeof AcquisitionsAcquisitionIdGridsGridIdSquaresRoute
  '/acquisitions/$acquisitionId/grids/$gridId/workspace': typeof AcquisitionsAcquisitionIdGridsGridIdWorkspaceRoute
  '/acquisitions/$acquisitionId/grids/$gridId': typeof AcquisitionsAcquisitionIdGridsGridIdIndexRoute
  '/acquisitions/$acquisitionId/grids/$gridId/squares/$squareId': typeof AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdIndexRoute
  '/acquisitions/$acquisitionId/grids/$gridId/squares/$squareId/holes/$holeId': typeof AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdHolesHoleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acquisitions': typeof AcquisitionsRouteWithChildren
  '/acquisitions/$acquisitionId': typeof AcquisitionsAcquisitionIdRouteWithChildren
  '/acquisitions/': typeof AcquisitionsIndexRoute
  '/acquisitions/$acquisitionId/': typeof AcquisitionsAcquisitionIdIndexRoute
  '/acquisitions/$acquisitionId/grids/$gridId': typeof AcquisitionsAcquisitionIdGridsGridIdRouteWithChildren
  '/acquisitions/$acquisitionId/grids/$gridId/atlas': typeof AcquisitionsAcquisitionIdGridsGridIdAtlasRoute
  '/acquisitions/$acquisitionId/grids/$gridId/predictions': typeof AcquisitionsAcquisitionIdGridsGridIdPredictionsRoute
  '/acquisitions/$acquisitionId/grids/$gridId/squares': typeof AcquisitionsAcquisitionIdGridsGridIdSquaresRoute
  '/acquisitions/$acquisitionId/grids/$gridId/workspace': typeof AcquisitionsAcquisitionIdGridsGridIdWorkspaceRoute
  '/acquisitions/$acquisitionId/grids/$gridId/': typeof AcquisitionsAcquisitionIdGridsGridIdIndexRoute
  '/acquisitions/$acquisitionId/grids/$gridId/squares_/$squareId': typeof AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdRouteWithChildren
  '/acquisitions/$acquisitionId/grids/$gridId/squares_/$squareId/': typeof AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdIndexRoute
  '/acquisitions/$acquisitionId/grids/$gridId/squares_/$squareId/holes_/$holeId': typeof AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdHolesHoleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acquisitions'
    | '/acquisitions/$acquisitionId'
    | '/acquisitions/'
    | '/acquisitions/$acquisitionId/'
    | '/acquisitions/$acquisitionId/grids/$gridId'
    | '/acquisitions/$acquisitionId/grids/$gridId/atlas'
    | '/acquisitions/$acquisitionId/grids/$gridId/predictions'
    | '/acquisitions/$acquisitionId/grids/$gridId/squares'
    | '/acquisitions/$acquisitionId/grids/$gridId/workspace'
    | '/acquisitions/$acquisitionId/grids/$gridId/'
    | '/acquisitions/$acquisitionId/grids/$gridId/squares/$squareId'
    | '/acquisitions/$acquisitionId/grids/$gridId/squares/$squareId/'
    | '/acquisitions/$acquisitionId/grids/$gridId/squares/$squareId/holes/$holeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acquisitions'
    | '/acquisitions/$acquisitionId'
    | '/acquisitions/$acquisitionId/grids/$gridId/atlas'
    | '/acquisitions/$acquisitionId/grids/$gridId/predictions'
    | '/acquisitions/$acquisitionId/grids/$gridId/squares'
    | '/acquisitions/$acquisitionId/grids/$gridId/workspace'
    | '/acquisitions/$acquisitionId/grids/$gridId'
    | '/acquisitions/$acquisitionId/grids/$gridId/squares/$squareId'
    | '/acquisitions/$acquisitionId/grids/$gridId/squares/$squareId/holes/$holeId'
  id:
    | '__root__'
    | '/'
    | '/acquisitions'
    | '/acquisitions/$acquisitionId'
    | '/acquisitions/'
    | '/acquisitions/$acquisitionId/'
    | '/acquisitions/$acquisitionId/grids/$gridId'
    | '/acquisitions/$acquisitionId/grids/$gridId/atlas'
    | '/acquisitions/$acquisitionId/grids/$gridId/predictions'
    | '/acquisitions/$acquisitionId/grids/$gridId/squares'
    | '/acquisitions/$acquisitionId/grids/$gridId/workspace'
    | '/acquisitions/$acquisitionId/grids/$gridId/'
    | '/acquisitions/$acquisitionId/grids/$gridId/squares_/$squareId'
    | '/acquisitions/$acquisitionId/grids/$gridId/squares_/$squareId/'
    | '/acquisitions/$acquisitionId/grids/$gridId/squares_/$squareId/holes_/$holeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcquisitionsRoute: typeof AcquisitionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/acquisitions': {
      id: '/acquisitions'
      path: '/acquisitions'
      fullPath: '/acquisitions'
      preLoaderRoute: typeof AcquisitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acquisitions/': {
      id: '/acquisitions/'
      path: '/'
      fullPath: '/acquisitions/'
      preLoaderRoute: typeof AcquisitionsIndexRouteImport
      parentRoute: typeof AcquisitionsRoute
    }
    '/acquisitions/$acquisitionId': {
      id: '/acquisitions/$acquisitionId'
      path: '/$acquisitionId'
      fullPath: '/acquisitions/$acquisitionId'
      preLoaderRoute: typeof AcquisitionsAcquisitionIdRouteImport
      parentRoute: typeof AcquisitionsRoute
    }
    '/acquisitions/$acquisitionId/': {
      id: '/acquisitions/$acquisitionId/'
      path: '/'
      fullPath: '/acquisitions/$acquisitionId/'
      preLoaderRoute: typeof AcquisitionsAcquisitionIdIndexRouteImport
      parentRoute: typeof AcquisitionsAcquisitionIdRoute
    }
    '/acquisitions/$acquisitionId/grids/$gridId': {
      id: '/acquisitions/$acquisitionId/grids/$gridId'
      path: '/grids/$gridId'
      fullPath: '/acquisitions/$acquisitionId/grids/$gridId'
      preLoaderRoute: typeof AcquisitionsAcquisitionIdGridsGridIdRouteImport
      parentRoute: typeof AcquisitionsAcquisitionIdRoute
    }
    '/acquisitions/$acquisitionId/grids/$gridId/': {
      id: '/acquisitions/$acquisitionId/grids/$gridId/'
      path: '/'
      fullPath: '/acquisitions/$acquisitionId/grids/$gridId/'
      preLoaderRoute: typeof AcquisitionsAcquisitionIdGridsGridIdIndexRouteImport
      parentRoute: typeof AcquisitionsAcquisitionIdGridsGridIdRoute
    }
    '/acquisitions/$acquisitionId/grids/$gridId/workspace': {
      id: '/acquisitions/$acquisitionId/grids/$gridId/workspace'
      path: '/workspace'
      fullPath: '/acquisitions/$acquisitionId/grids/$gridId/workspace'
      preLoaderRoute: typeof AcquisitionsAcquisitionIdGridsGridIdWorkspaceRouteImport
      parentRoute: typeof AcquisitionsAcquisitionIdGridsGridIdRoute
    }
    '/acquisitions/$acquisitionId/grids/$gridId/squares': {
      id: '/acquisitions/$acquisitionId/grids/$gridId/squares'
      path: '/squares'
      fullPath: '/acquisitions/$acquisitionId/grids/$gridId/squares'
      preLoaderRoute: typeof AcquisitionsAcquisitionIdGridsGridIdSquaresRouteImport
      parentRoute: typeof AcquisitionsAcquisitionIdGridsGridIdRoute
    }
    '/acquisitions/$acquisitionId/grids/$gridId/predictions': {
      id: '/acquisitions/$acquisitionId/grids/$gridId/predictions'
      path: '/predictions'
      fullPath: '/acquisitions/$acquisitionId/grids/$gridId/predictions'
      preLoaderRoute: typeof AcquisitionsAcquisitionIdGridsGridIdPredictionsRouteImport
      parentRoute: typeof AcquisitionsAcquisitionIdGridsGridIdRoute
    }
    '/acquisitions/$acquisitionId/grids/$gridId/atlas': {
      id: '/acquisitions/$acquisitionId/grids/$gridId/atlas'
      path: '/atlas'
      fullPath: '/acquisitions/$acquisitionId/grids/$gridId/atlas'
      preLoaderRoute: typeof AcquisitionsAcquisitionIdGridsGridIdAtlasRouteImport
      parentRoute: typeof AcquisitionsAcquisitionIdGridsGridIdRoute
    }
    '/acquisitions/$acquisitionId/grids/$gridId/squares_/$squareId': {
      id: '/acquisitions/$acquisitionId/grids/$gridId/squares_/$squareId'
      path: '/squares/$squareId'
      fullPath: '/acquisitions/$acquisitionId/grids/$gridId/squares/$squareId'
      preLoaderRoute: typeof AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdRouteImport
      parentRoute: typeof AcquisitionsAcquisitionIdGridsGridIdRoute
    }
    '/acquisitions/$acquisitionId/grids/$gridId/squares_/$squareId/': {
      id: '/acquisitions/$acquisitionId/grids/$gridId/squares_/$squareId/'
      path: '/'
      fullPath: '/acquisitions/$acquisitionId/grids/$gridId/squares/$squareId/'
      preLoaderRoute: typeof AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdIndexRouteImport
      parentRoute: typeof AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdRoute
    }
    '/acquisitions/$acquisitionId/grids/$gridId/squares_/$squareId/holes_/$holeId': {
      id: '/acquisitions/$acquisitionId/grids/$gridId/squares_/$squareId/holes_/$holeId'
      path: '/holes/$holeId'
      fullPath: '/acquisitions/$acquisitionId/grids/$gridId/squares/$squareId/holes/$holeId'
      preLoaderRoute: typeof AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdHolesHoleIdRouteImport
      parentRoute: typeof AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdRoute
    }
  }
}

interface AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdRouteChildren {
  AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdIndexRoute: typeof AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdIndexRoute
  AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdHolesHoleIdRoute: typeof AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdHolesHoleIdRoute
}

const AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdRouteChildren: AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdRouteChildren =
  {
    AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdIndexRoute:
      AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdIndexRoute,
    AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdHolesHoleIdRoute:
      AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdHolesHoleIdRoute,
  }

const AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdRouteWithChildren =
  AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdRoute._addFileChildren(
    AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdRouteChildren,
  )

interface AcquisitionsAcquisitionIdGridsGridIdRouteChildren {
  AcquisitionsAcquisitionIdGridsGridIdAtlasRoute: typeof AcquisitionsAcquisitionIdGridsGridIdAtlasRoute
  AcquisitionsAcquisitionIdGridsGridIdPredictionsRoute: typeof AcquisitionsAcquisitionIdGridsGridIdPredictionsRoute
  AcquisitionsAcquisitionIdGridsGridIdSquaresRoute: typeof AcquisitionsAcquisitionIdGridsGridIdSquaresRoute
  AcquisitionsAcquisitionIdGridsGridIdWorkspaceRoute: typeof AcquisitionsAcquisitionIdGridsGridIdWorkspaceRoute
  AcquisitionsAcquisitionIdGridsGridIdIndexRoute: typeof AcquisitionsAcquisitionIdGridsGridIdIndexRoute
  AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdRoute: typeof AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdRouteWithChildren
}

const AcquisitionsAcquisitionIdGridsGridIdRouteChildren: AcquisitionsAcquisitionIdGridsGridIdRouteChildren =
  {
    AcquisitionsAcquisitionIdGridsGridIdAtlasRoute:
      AcquisitionsAcquisitionIdGridsGridIdAtlasRoute,
    AcquisitionsAcquisitionIdGridsGridIdPredictionsRoute:
      AcquisitionsAcquisitionIdGridsGridIdPredictionsRoute,
    AcquisitionsAcquisitionIdGridsGridIdSquaresRoute:
      AcquisitionsAcquisitionIdGridsGridIdSquaresRoute,
    AcquisitionsAcquisitionIdGridsGridIdWorkspaceRoute:
      AcquisitionsAcquisitionIdGridsGridIdWorkspaceRoute,
    AcquisitionsAcquisitionIdGridsGridIdIndexRoute:
      AcquisitionsAcquisitionIdGridsGridIdIndexRoute,
    AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdRoute:
      AcquisitionsAcquisitionIdGridsGridIdSquaresSquareIdRouteWithChildren,
  }

const AcquisitionsAcquisitionIdGridsGridIdRouteWithChildren =
  AcquisitionsAcquisitionIdGridsGridIdRoute._addFileChildren(
    AcquisitionsAcquisitionIdGridsGridIdRouteChildren,
  )

interface AcquisitionsAcquisitionIdRouteChildren {
  AcquisitionsAcquisitionIdIndexRoute: typeof AcquisitionsAcquisitionIdIndexRoute
  AcquisitionsAcquisitionIdGridsGridIdRoute: typeof AcquisitionsAcquisitionIdGridsGridIdRouteWithChildren
}

const AcquisitionsAcquisitionIdRouteChildren: AcquisitionsAcquisitionIdRouteChildren =
  {
    AcquisitionsAcquisitionIdIndexRoute: AcquisitionsAcquisitionIdIndexRoute,
    AcquisitionsAcquisitionIdGridsGridIdRoute:
      AcquisitionsAcquisitionIdGridsGridIdRouteWithChildren,
  }

const AcquisitionsAcquisitionIdRouteWithChildren =
  AcquisitionsAcquisitionIdRoute._addFileChildren(
    AcquisitionsAcquisitionIdRouteChildren,
  )

interface AcquisitionsRouteChildren {
  AcquisitionsAcquisitionIdRoute: typeof AcquisitionsAcquisitionIdRouteWithChildren
  AcquisitionsIndexRoute: typeof AcquisitionsIndexRoute
}

const AcquisitionsRouteChildren: AcquisitionsRouteChildren = {
  AcquisitionsAcquisitionIdRoute: AcquisitionsAcquisitionIdRouteWithChildren,
  AcquisitionsIndexRoute: AcquisitionsIndexRoute,
}

const AcquisitionsRouteWithChildren = AcquisitionsRoute._addFileChildren(
  AcquisitionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcquisitionsRoute: AcquisitionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
